In [12]:
import pandas as pd 
import xml.etree.ElementTree as et 

xtree = et.parse("Badges.xml")
xroot = xtree.getroot() 

df_cols = ["Id", "UserId", "Name", "Date","Class","TagBased"]
rows = []

for node in xroot: 
    s_Id = node.attrib.get("Id")
    s_UserId = node.get("UserId") if node is not None else None
    s_Name = node.get("Name") if node is not None else None
    s_Date = node.get("Date") if node is not None else None
    s_Class = node.get("Class") if node is not None else None
    s_TagBased = node.get("TagBased") if node is not None else None
#     s_age = node.find("age").text if node is not None else None
    
    rows.append({"Id": s_Id, "UserId": s_UserId, 
                 "Name": s_Name, "Date": s_Date, 
                 "Class": s_Class, "TagBased": s_TagBased})

out_df = pd.DataFrame(rows, columns = df_cols)

In [15]:
out_df.head()

Id UserId            Name                     Date Class TagBased
0  1      1        Informed  2014-05-13T23:06:44.683     3    False
1  2      2  Autobiographer  2014-05-13T23:11:04.153     3    False
2  3      4  Autobiographer  2014-05-13T23:20:53.547     3    False
3  4      5  Autobiographer  2014-05-13T23:20:53.547     3    False
4  5      8  Autobiographer  2014-05-13T23:20:53.547     3    False

In [14]:
out_df.to_csv (r'Badges.csv', index = None, header=True)

In [17]:
import pandas as pd 
import xml.etree.ElementTree as et 

xtree = et.parse("Comments.xml")
xroot = xtree.getroot() 

df_cols = ["Id", "PostId", "Score", "Text","CreationDate","UserId"]
rows = []

for node in xroot: 
    s_Id = node.attrib.get("Id")
    s_PostId = node.get("PostId") if node is not None else None
    s_Score = node.get("Score") if node is not None else None
    s_Text = node.get("Text") if node is not None else None
    s_CreationDate = node.get("CreationDate") if node is not None else None
    s_UserId = node.get("UserId") if node is not None else None
#     s_age = node.find("age").text if node is not None else None
    
    rows.append({"Id": s_Id, "PostId": s_PostId, 
                 "Score": s_Score, "Text": s_Text, 
                 "CreationDate": s_CreationDate, "UserId": s_UserId})

out_df2 = pd.DataFrame(rows, columns = df_cols)

In [18]:
out_df2.head()

Id PostId Score                                               Text  \
0   5      5     9  this is a super theoretical AI question. An in...   
1   6      7     4  List questions are usually not suited for Stac...   
2   9      7     3  This question appears to be off-topic because ...   
3  12     15     3  This question is far too broad. It may be salv...   
4  13     10     2  Nice one, @Nicholas... Another book from Hasti...   

              CreationDate UserId  
0  2014-05-14T00:23:15.437     34  
1  2014-05-14T00:38:19.510     51  
2  2014-05-14T01:16:12.623     66  
3  2014-05-14T02:00:22.797     51  
4  2014-05-14T02:16:20.503     24

In [19]:
out_df2.to_csv (r'Comments.csv', index = None, header=True)

In [22]:
import pandas as pd 
import xml.etree.ElementTree as et 

xtree = et.parse("PostHistory.xml")
xroot = xtree.getroot() 

df_cols = ["Id", "PostHistoryTypeId", "PostId", "RevisionGUID","CreationDate","UserId","Text"]
rows = []

for node in xroot: 
    s_Id = node.attrib.get("Id")
    s_PostHistoryTypeId = node.get("PostHistoryTypeId") if node is not None else None
    s_PostId = node.get("PostId") if node is not None else None
    s_RevisionGUID = node.get("RevisionGUID") if node is not None else None
    s_CreationDate = node.get("CreationDate") if node is not None else None
    s_UserId = node.get("UserId") if node is not None else None
    s_Text = node.get("Text") if node is not None else None
#     s_age = node.get("age") if node is not None else None
    
    rows.append({"Id": s_Id, "PostHistoryTypeId": s_PostHistoryTypeId, 
                 "PostId": s_PostId, "RevisionGUID": s_RevisionGUID, 
                 "CreationDate": s_CreationDate, "UserId": s_UserId,"Text": s_Text})

out_df3 = pd.DataFrame(rows, columns = df_cols)

In [23]:
out_df3.head()

Id PostHistoryTypeId PostId                          RevisionGUID  \
0   7                 2      5  009bca93-fce2-44ed-a277-a8452650a627   
1   8                 1      5  009bca93-fce2-44ed-a277-a8452650a627   
2   9                 3      5  009bca93-fce2-44ed-a277-a8452650a627   
3  12                 2      7  ea5a5642-ed30-43ea-9be5-8e8de0e1c660   
4  13                 1      7  ea5a5642-ed30-43ea-9be5-8e8de0e1c660   

              CreationDate UserId  \
0  2014-05-13T23:58:30.457      5   
1  2014-05-13T23:58:30.457      5   
2  2014-05-13T23:58:30.457      5   
3  2014-05-14T00:11:06.457     36   
4  2014-05-14T00:11:06.457     36   

                                                Text  
0  I've always been interested in machine learnin...  
1  How can I do simple machine learning without h...  
2                                 <machine-learning>  
3  As a researcher and instructor, I'm looking fo...  
4  What open-source books (or other materials) pr...

In [24]:
out_df3.to_csv (r'PostHistory.csv', index = None, header=True)

In [25]:
import pandas as pd 
import xml.etree.ElementTree as et 

xtree = et.parse("PostLinks.xml")
xroot = xtree.getroot() 

df_cols = ["Id", "CreationDate", "PostId", "RelatedPostId","LinkTypeId"]
rows = []

for node in xroot: 
    s_Id = node.attrib.get("Id")
    s_CreationDate = node.get("CreationDate") if node is not None else None
    s_PostId = node.get("PostId") if node is not None else None
    s_RelatedPostId = node.get("RelatedPostId") if node is not None else None
    s_LinkTypeId = node.get("LinkTypeId") if node is not None else None
    s_Text = node.get("Text") if node is not None else None
#     s_age = node.get("age") if node is not None else None
    
    rows.append({"Id": s_Id, "CreationDate": s_CreationDate, 
                 "PostId": s_PostId, "RelatedPostId": s_RelatedPostId, "LinkTypeId": s_LinkTypeId})

out_df4 = pd.DataFrame(rows, columns = df_cols)

In [26]:
out_df4.head()

Id             CreationDate PostId RelatedPostId LinkTypeId
0    9  2014-05-14T07:56:34.437     14             1          1
1   50  2014-05-15T01:46:28.467     75            71          1
2  172  2014-05-20T17:42:19.287     59            41          1
3  387  2014-06-13T16:44:29.323    361            61          1
4  392  2014-06-13T16:58:23.247     61           361          1

In [27]:
out_df4.to_csv (r'PostLinks.csv', index = None, header=True)

In [30]:
import pandas as pd 
import xml.etree.ElementTree as et 

xtree = et.parse("Posts.xml")
xroot = xtree.getroot() 

df_cols = ["Id", "PostTypeId", "CreationDate", "Score","ViewCount","Body","OwnerUserId","LastActivityDate","Title","Tags","AnswerCount","CommentCount","FavoriteCount","ClosedDate"]
rows = []

for node in xroot: 
    s_Id = node.attrib.get("Id")
    s_PostTypeId = node.get("PostTypeId") if node is not None else None
    s_CreationDate = node.get("CreationDate") if node is not None else None
    s_Score = node.get("Score") if node is not None else None
    s_ViewCount = node.get("ViewCount") if node is not None else None
    s_Body = node.get("Body") if node is not None else None
    s_OwnerUserId = node.get("OwnerUserId") if node is not None else None
    s_LastActivityDate = node.get("LastActivityDate") if node is not None else None
    s_Title = node.get("Title") if node is not None else None
    s_Tags = node.get("Tags") if node is not None else None
    s_AnswerCount = node.get("AnswerCount") if node is not None else None
    s_CommentCount = node.get("CommentCount") if node is not None else None
    s_FavoriteCount = node.get("FavoriteCount") if node is not None else None
    s_ClosedDate = node.get("ClosedDate") if node is not None else None
#     s_age = node.get("age") if node is not None else None
    
    rows.append({"Id": s_Id, "PostTypeId": s_PostTypeId, 
                 "CreationDate": s_CreationDate, "Score": s_Score, 
                 "ViewCount": s_ViewCount, "Body": s_Body,"OwnerUserId": s_OwnerUserId,"LastActivityDate": s_LastActivityDate,"Title": s_Title,"Tags": s_Tags,"AnswerCount": s_AnswerCount,"CommentCount": s_CommentCount,"FavoriteCount": s_FavoriteCount,"ClosedDate": s_ClosedDate})

out_df5 = pd.DataFrame(rows, columns = df_cols)

In [31]:
out_df5.head()

Id PostTypeId             CreationDate Score ViewCount  \
0   5          1  2014-05-13T23:58:30.457     8       604   
1   7          1  2014-05-14T00:11:06.457     4       426   
2   9          2  2014-05-14T00:36:31.077     5      None   
3  10          2  2014-05-14T00:53:43.273    12      None   
4  14          1  2014-05-14T01:25:59.677    23      1495   

                                                Body OwnerUserId  \
0  <p>I've always been interested in machine lear...           5   
1  <p>As a researcher and instructor, I'm looking...          36   
2  <p>Not sure if this fits the scope of this SE,...          51   
3  <p>One book that's freely available is "The El...          22   
4  <p>I am sure data science as will be discussed...          66   

          LastActivityDate                                              Title  \
0  2014-05-14T00:36:31.077  How can I do simple machine learning without h...   
1  2014-05-16T13:45:00.237  What open-source books (or other materials) pr...   
2  2014-05-14T00:36:31.077                                               None   
3  2014-05-14T00:53:43.273                                               None   
4  2014-06-20T17:36:05.023           Is Data Science the Same as Data Mining?   

                         Tags AnswerCount CommentCount FavoriteCount  \
0          <machine-learning>           1            1             1   
1    <education><open-source>           3            4             1   
2                        None        None            0          None   
3                        None        None            1          None   
4  <data-mining><definitions>           4            1             6   

                ClosedDate  
0  2014-05-14T14:40:25.950  
1  2014-05-14T08:40:54.950  
2                     None  
3                     None  
4                     None

In [32]:
out_df5.to_csv (r'Posts.csv', index = None, header=True)

In [33]:
import pandas as pd 
import xml.etree.ElementTree as et 

xtree = et.parse("Tags.xml")
xroot = xtree.getroot() 

df_cols = ["Id", "TagName", "Count", "ExcerptPostId","WikiPostId"]
rows = []

for node in xroot: 
    s_Id = node.attrib.get("Id")
    s_TagName = node.get("TagName") if node is not None else None
    s_Count = node.get("Count") if node is not None else None
    s_ExcerptPostId = node.get("ExcerptPostId") if node is not None else None
    s_WikiPostId = node.get("WikiPostId") if node is not None else None
    s_UserId = node.get("UserId") if node is not None else None
#     s_age = node.find("age").ExcerptPostId if node is not None else None
    
    rows.append({"Id": s_Id, "TagName": s_TagName, 
                 "Count": s_Count, "ExcerptPostId": s_ExcerptPostId, 
                 "WikiPostId": s_WikiPostId})

out_df6 = pd.DataFrame(rows, columns = df_cols)

In [34]:
out_df6.head()

Id           TagName Count ExcerptPostId WikiPostId
0  1       definitions    26           105        104
1  2  machine-learning  6024          4909       4908
2  3           bigdata   390            66         65
3  5       data-mining   865            80         79
4  6         databases    70          8960       8959

In [35]:
out_df6.to_csv (r'Tags.csv', index = None, header=True)

In [27]:
import pandas as pd 
import xml.etree.ElementTree as et 

xtree = et.parse("Users.xml")
xroot = xtree.getroot() 

df_cols = ["Id", "Reputation", "CreationDate", "DisplayName","LastAccessDate","WebsiteUrl","Location","AboutMe","Views","UpVotes","DownVotes","AccountId"]
rows = []

for node in xroot: 
    s_Id = node.attrib.get("Id")
    s_Reputation = node.get("Reputation") if node is not None else None
    s_CreationDate = node.get("CreationDate") if node is not None else None
    s_DisplayName = node.get("DisplayName") if node is not None else None
    s_LastAccessDate = node.get("LastAccessDate") if node is not None else None
    s_WebsiteUrl = node.get("WebsiteUrl") if node is not None else None
    s_Location = node.get("Location") if node is not None else None
    s_AboutMe = node.get("AboutMe") if node is not None else None
    s_Views = node.get("Views") if node is not None else None
    s_UpVotes = node.get("UpVotes") if node is not None else None
    s_DownVotes = node.get("DownVotes") if node is not None else None
    s_AccountId = node.get("AccountId") if node is not None else None
#     s_FavoriteCount = node.get("FavoriteCount") if node is not None else None
#     s_ClosedDate = node.get("ClosedDate") if node is not None else None
#     s_age = node.get("age") if node is not None else None
    
    rows.append({"Id": s_Id, "Reputation": s_Reputation, 
                 "CreationDate": s_CreationDate, "DisplayName": s_DisplayName, 
                 "LastAccessDate": s_LastAccessDate, "WebsiteUrl": s_WebsiteUrl,"Location": s_Location,"AboutMe": s_AboutMe,"Views": s_Views,"UpVotes": s_UpVotes,"DownVotes": s_DownVotes,"AccountId": s_AccountId})

out_df7 = pd.DataFrame(rows, columns = df_cols)

In [28]:
out_df7.head()

Id Reputation             CreationDate   DisplayName  \
0  -1          1  2014-05-13T21:29:22.820     Community   
1   1        101  2014-05-13T22:58:54.810     Adam Lear   
2   2        101  2014-05-13T22:59:19.787  Geoff Dalgas   
3   3        101  2014-05-13T23:15:34.483    hichris123   
4   4        101  2014-05-13T23:16:09.937   Ben Collins   

            LastAccessDate                      WebsiteUrl  \
0  2014-05-13T21:29:22.820  http://meta.stackexchange.com/   
1  2019-06-11T19:12:27.157                            None   
2  2017-12-19T18:52:19.423        http://stackoverflow.com   
3  2019-08-01T18:06:24.597                            None   
4  2014-08-04T15:25:54.810      http://benjamincollins.com   

             Location                                            AboutMe  \
0  on the server farm  <p>Hi, I'm not really a person.</p>\n\n<p>I'm ...   
1        New York, NY  \n\n<p>Developer at Stack Overflow focusing on...   
2       Corvallis, OR  <p>Developer on the Stack Overflow team.  Find...   
3                None  <p>I'm a student interested in technology.</p>...   
4   Republic of Texas  <p>I work with <a href="https://olo.com" rel="...   

  Views UpVotes DownVotes AccountId  
0     0     798      1325        -1  
1   453       0         0     37099  
2     9       0         0         2  
3     7       1         3   3046327  
4     9       0         0      2365

In [29]:
out_df7.to_csv (r'Users.csv', index = None, header=True)

In [39]:
import pandas as pd 
import xml.etree.ElementTree as et 

xtree = et.parse("Votes.xml")
xroot = xtree.getroot() 

df_cols = ["Id", "PostId", "VoteTypeId", "CreationDate"]
rows = []

for node in xroot: 
    s_Id = node.attrib.get("Id")
    s_PostId = node.get("PostId") if node is not None else None
    s_VoteTypeId = node.get("VoteTypeId") if node is not None else None
    s_CreationDate = node.get("CreationDate") if node is not None else None
#     s_Class = node.get("Class") if node is not None else None
#     s_TagBased = node.get("TagBased") if node is not None else None
#     s_age = node.find("age").text if node is not None else None
    
    rows.append({"Id": s_Id, "PostId": s_PostId, 
                 "VoteTypeId": s_VoteTypeId, "CreationDate": s_CreationDate})

out_df8 = pd.DataFrame(rows, columns = df_cols)

In [40]:
out_df8.head()

Id PostId VoteTypeId             CreationDate
0  1      1          2  2014-05-13T00:00:00.000
1  2      1          2  2014-05-13T00:00:00.000
2  3      3          2  2014-05-13T00:00:00.000
3  5      3          2  2014-05-13T00:00:00.000
4  6      1          2  2014-05-13T00:00:00.000

In [41]:
out_df8.to_csv (r'Votes.csv', index = None, header=True)

In [1]:
import pandas as pd 

In [3]:
df = pd.read_csv('Votes.csv')

In [ ]:
df.head(2)

In [25]:
df = pd.read_csv('Badges.csv')

In [5]:
df.head(2)

Id  PostTypeId             CreationDate  Score  ViewCount  \
0   5           1  2014-05-13T23:58:30.457      8      604.0   
1   7           1  2014-05-14T00:11:06.457      4      426.0   

                                                Body  OwnerUserId  \
0  <p>I've always been interested in machine lear...          5.0   
1  <p>As a researcher and instructor, I'm looking...         36.0   

          LastActivityDate                                              Title  \
0  2014-05-14T00:36:31.077  How can I do simple machine learning without h...   
1  2014-05-16T13:45:00.237  What open-source books (or other materials) pr...   

                       Tags  AnswerCount  CommentCount  FavoriteCount  \
0        <machine-learning>          1.0             1            1.0   
1  <education><open-source>          3.0             4            1.0   

                ClosedDate  
0  2014-05-14T14:40:25.950  
1  2014-05-14T08:40:54.950

In [7]:
df = pd.read_csv('Comments.csv')

In [42]:
df = pd.read_csv('PostHistory.csv')

In [2]:
df = pd.read_csv('PostLinks.csv')

In [4]:
df = pd.read_csv('Posts.csv')

In [ ]:
df.head(200)

In [34]:
df = pd.read_csv('Tags.csv')

In [35]:
df.head(2)

Id           TagName  Count  ExcerptPostId  WikiPostId
0   1       definitions     26          105.0       104.0
1   2  machine-learning   6024         4909.0      4908.0

In [20]:
df = pd.read_csv('Votes.csv')

In [36]:
df = pd.read_csv('Users.csv')

In [37]:
df.head(3)

Id  Reputation             CreationDate   DisplayName  \
0  -1           1  2014-05-13T21:29:22.820     Community   
1   1         101  2014-05-13T22:58:54.810     Adam Lear   
2   2         101  2014-05-13T22:59:19.787  Geoff Dalgas   

            LastAccessDate                      WebsiteUrl  \
0  2014-05-13T21:29:22.820  http://meta.stackexchange.com/   
1  2019-06-11T19:12:27.157                             NaN   
2  2017-12-19T18:52:19.423        http://stackoverflow.com   

             Location                                            AboutMe  \
0  on the server farm  <p>Hi, I'm not really a person.</p>\n\n<p>I'm ...   
1        New York, NY  \n\n<p>Developer at Stack Overflow focusing on...   
2       Corvallis, OR  <p>Developer on the Stack Overflow team.  Find...   

   Views  UpVotes  DownVotes  AccountId  
0      0      798       1325       -1.0  
1    453        0          0    37099.0  
2      9        0          0        2.0

In [1]:
d1 = "plot: two teen couples go to a church party, drink and then drive."
d2 = "films adapted from comic books have had plenty of success , whether they're about superheroes ( batman , superman , spawn ) , or geared toward kids ( casper ) or the arthouse crowd ( ghost world ) , but there's never really been a comic book like from hell before . "
d3 = "every now and then a movie comes along from a suspect studio , with every indication that it will be a stinker , and to everybody's surprise ( perhaps even the studio ) the film becomes a critical darling . "
d4 = "damn that y2k bug . "
documents = [d1, d2, d3, d4]

In [4]:
documents

['plot: two teen couples go to a church party, drink and then drive.',
 "films adapted from comic books have had plenty of success , whether they're about superheroes ( batman , superman , spawn ) , or geared toward kids ( casper ) or the arthouse crowd ( ghost world ) , but there's never really been a comic book like from hell before . ",
 "every now and then a movie comes along from a suspect studio , with every indication that it will be a stinker , and to everybody's surprise ( perhaps even the studio ) the film becomes a critical darling . ",
 'damn that y2k bug . ']

In [5]:
import nltk, string, numpy
# nltk.download('punkt') # first-time use only
stemmer = nltk.stem.porter.PorterStemmer()
def StemTokens(tokens):
    return [stemmer.stem(token) for token in tokens]
remove_punct_dict = dict((ord(punct), None) for punct in string.punctuation)
def StemNormalize(text):
    return StemTokens(nltk.word_tokenize(text.lower().translate(remove_punct_dict)))

In [9]:
# nltk.download('wordnet') # first-time use only
lemmer = nltk.stem.WordNetLemmatizer()
def LemTokens(tokens):
    return [lemmer.lemmatize(token) for token in tokens]
remove_punct_dict = dict((ord(punct), None) for punct in string.punctuation)
def LemNormalize(text):
    return LemTokens(nltk.word_tokenize(text.lower().translate(remove_punct_dict)))

In [10]:
from sklearn.feature_extraction.text import CountVectorizer
LemVectorizer = CountVectorizer(tokenizer=LemNormalize, stop_words='english')
LemVectorizer.fit_transform(documents)

C:\Users\nikita\Anaconda3\lib\site-packages\sklearn\feature_extraction\text.py:300: UserWarning: Your stop_words may be inconsistent with your preprocessing. Tokenizing the stop words generated tokens ['ha', 'le', 'u', 'wa'] not in stop_words.
  'stop_words.' % sorted(inconsistent))


<4x41 sparse matrix of type '<class 'numpy.int64'>'
	with 42 stored elements in Compressed Sparse Row format>

In [14]:
print(LemVectorizer.vocabulary_)

{'plot': 27, 'teen': 37, 'couple': 9, 'church': 6, 'party': 25, 'drink': 14, 'drive': 15, 'film': 17, 'adapted': 0, 'comic': 8, 'book': 3, 'plenty': 26, 'success': 32, 'theyre': 38, 'superheroes': 33, 'batman': 2, 'superman': 34, 'spawn': 29, 'geared': 18, 'kid': 22, 'casper': 5, 'arthouse': 1, 'crowd': 11, 'ghost': 19, 'world': 39, 'really': 28, 'like': 23, 'hell': 20, 'movie': 24, 'come': 7, 'suspect': 36, 'studio': 31, 'indication': 21, 'stinker': 30, 'everybodys': 16, 'surprise': 35, 'critical': 10, 'darling': 13, 'damn': 12, 'y2k': 40, 'bug': 4}


In [23]:
documents

['plot: two teen couples go to a church party, drink and then drive.',
 "films adapted from comic books have had plenty of success , whether they're about superheroes ( batman , superman , spawn ) , or geared toward kids ( casper ) or the arthouse crowd ( ghost world ) , but there's never really been a comic book like from hell before . ",
 "every now and then a movie comes along from a suspect studio , with every indication that it will be a stinker , and to everybody's surprise ( perhaps even the studio ) the film becomes a critical darling . ",
 'damn that y2k bug . ']

In [16]:
tf_matrix = LemVectorizer.transform(documents).toarray()
print(tf_matrix)

[[0 0 0 0 0 0 1 0 0 1 0 0 0 0 1 1 0 0 0 0 0 0 0 0 0 1 0 1 0 0 0 0 0 0 0 0
  0 1 0 0 0]
 [1 1 1 2 0 1 0 0 2 0 0 1 0 0 0 0 0 1 1 1 1 0 1 1 0 0 1 0 1 1 0 0 1 1 1 0
  0 0 1 1 0]
 [0 0 0 0 0 0 0 1 0 0 1 0 0 1 0 0 1 1 0 0 0 1 0 0 1 0 0 0 0 0 1 2 0 0 0 1
  1 0 0 0 0]
 [0 0 0 0 1 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 1]]


In [18]:
from sklearn.feature_extraction.text import TfidfTransformer
tfidfTran = TfidfTransformer(norm="l2")
tfidfTran.fit(tf_matrix)
print(tfidfTran.idf_)

[1.91629073 1.91629073 1.91629073 1.91629073 1.91629073 1.91629073
 1.91629073 1.91629073 1.91629073 1.91629073 1.91629073 1.91629073
 1.91629073 1.91629073 1.91629073 1.91629073 1.91629073 1.51082562
 1.91629073 1.91629073 1.91629073 1.91629073 1.91629073 1.91629073
 1.91629073 1.91629073 1.91629073 1.91629073 1.91629073 1.91629073
 1.91629073 1.91629073 1.91629073 1.91629073 1.91629073 1.91629073
 1.91629073 1.91629073 1.91629073 1.91629073 1.91629073]


In [19]:
import math
def idf(n,df):
    result = math.log((n+1.0)/(df+1.0)) + 1
    return result
print("The idf for terms that appear in one document: " + str(idf(4,1)))
print("The idf for terms that appear in two documents: " + str(idf(4,2)))

The idf for terms that appear in one document: 1.916290731874155
The idf for terms that appear in two documents: 1.5108256237659907


In [20]:
tfidf_matrix = tfidfTran.transform(tf_matrix)
print(tfidf_matrix.toarray())

[[0.         0.         0.         0.         0.         0.
  0.37796447 0.         0.         0.37796447 0.         0.
  0.         0.         0.37796447 0.37796447 0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.37796447 0.         0.37796447 0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.37796447 0.         0.         0.        ]
 [0.19381304 0.19381304 0.19381304 0.38762607 0.         0.19381304
  0.         0.         0.38762607 0.         0.         0.19381304
  0.         0.         0.         0.         0.         0.15280442
  0.19381304 0.19381304 0.19381304 0.         0.19381304 0.19381304
  0.         0.         0.19381304 0.         0.19381304 0.19381304
  0.         0.         0.19381304 0.19381304 0.19381304 0.
  0.         0.         0.19381304 0.19381304 0.        ]
 [0.         0.         0.         0.         0.         0.
  0.         0.27094807 0.         0.         0.27094807 0.
  0.

In [43]:
tfidf_matrix.shape
# tfidf_matrix.T.shape
tfidf_matrix[1]

<1x41 sparse matrix of type '<class 'numpy.float64'>'
	with 21 stored elements in Compressed Sparse Row format>

In [22]:
cos_similarity_matrix = (tfidf_matrix * tfidf_matrix.T).toarray()
print(cos_similarity_matrix)

[[1.         0.         0.         0.        ]
 [0.         1.         0.03264186 0.        ]
 [0.         0.03264186 1.         0.        ]
 [0.         0.         0.         1.        ]]


In [29]:
import numpy as np

In [65]:
# tfidf_matrix1 = []
tfidf_matrix1 = np.zeros((10531, 489))

In [66]:
type(tfidf_matrix)

scipy.sparse.csr.csr_matrix

In [68]:
cos_similarity_matrix = (tfidf_matrix1.dot(tfidf_matrix1.T))
print(cos_similarity_matrix)

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


In [69]:
cos_similarity_matrix.shape

(10531, 10531)